version: '3'
services:
  tokenlysis:
    container_name: tokenlysis
    build:
      context: https://github.com/<owner>/Tokenlysis.git#main
    ports:
      - "8000:8000"
    restart: unless-stopped
