services:
  tokenlysis:
    container_name: tokenlysis
    image: tokenlysis:${APP_VERSION:-dev}
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
    ports:
      - "8002:8000"
    restart: unless-stopped
