version: '3'
services:
  tokenlysis:
    container_name: tokenlysis
    build:
      context: .
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    environment:
      - CORS_ORIGINS=http://localhost
    ports:
      - "8002:8000"
    restart: unless-stopped
