version: '3'
services:
  tokenlysis:
    container_name: tokenlysis
    build:
      context: https://github.com/Tomp0uce/Tokenlysis.git#main
      dockerfile: Dockerfile.synology
      args:
        APP_VERSION: "${APP_VERSION:-dev}"
    environment:
      - CORS_ORIGINS=http://localhost
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
    ports:
      - "8002:8000"
    restart: unless-stopped
