name: Build images with run number version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_VERSION: 1.0.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute build vars
        run: |
          echo "GIT_COMMIT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

      - name: Show computed version
        run: |
          echo "APP_VERSION=$APP_VERSION"
          echo "GIT_COMMIT=$GIT_COMMIT"
          echo "BUILD_TIME=$BUILD_TIME"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Build local pour validation (pas de push)
      - name: Build Docker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          load: true
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
            BUILD_TIME=${{ env.BUILD_TIME }}
          labels: |
            org.opencontainers.image.version=${{ env.APP_VERSION }}
            org.opencontainers.image.revision=${{ env.GIT_COMMIT }}
            org.opencontainers.image.created=${{ env.BUILD_TIME }}

      # --- Variante PUSH (décommente pour publier sur GHCR) ---
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #
      # - name: Build & Push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: true
      #     build-args: |
      #       APP_VERSION=${{ env.APP_VERSION }}
      #       GIT_COMMIT=${{ env.GIT_COMMIT }}
      #       BUILD_TIME=${{ env.BUILD_TIME }}
      #     tags: |
      #       ghcr.io/${{ github.repository_owner }}/tokenlysis:${{ env.APP_VERSION }}
      #       ghcr.io/${{ github.repository_owner }}/tokenlysis:latest
      #     labels: |
      #       org.opencontainers.image.version=${{ env.APP_VERSION }}
      #       org.opencontainers.image.revision=${{ env.GIT_COMMIT }}
      #       org.opencontainers.image.created=${{ env.BUILD_TIME }}
